// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    daily_clv_at_risk: {
        name: "daily_clv_at_risk";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          return_date: string;
          /** @sqlType DOUBLE */
          clv_at_risk_usd: number;
        }>;
      };
    atrisk_by_plan: {
        name: "atrisk_by_plan";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          plan_type: string;
          /** @sqlType BIGINT */
          subscriber_count: number;
          /** @sqlType DOUBLE */
          clv_at_risk_usd: number;
        }>;
      };
    atrisk_by_metro: {
        name: "atrisk_by_metro";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          home_metro: string;
          /** @sqlType BIGINT */
          subscriber_count: number;
          /** @sqlType DOUBLE */
          clv_at_risk_usd: number;
        }>;
      };
    worst_nodes: {
        name: "worst_nodes";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          service_node_id: string;
          /** @sqlType STRING */
          home_metro: string;
          /** @sqlType BIGINT */
          subscribers: number;
          /** @sqlType BIGINT */
          atrisk_count: number;
          /** @sqlType DOUBLE */
          atrisk_rate_pct: number;
          /** @sqlType DOUBLE */
          clv_at_risk_usd: number;
        }>;
      };
  }
}
